[package]
name = "confql"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/all.rs"

[dev-dependencies]
trybuild = { version = "1.0", features = ["diff"] }