[package]
name = "test-utils"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "1.0.3"
serde_yaml = "0.8.21"

[dev-dependencies]
anyhow = "1.0.44"
